/*
** Copyright 2012-2020 Double Precision, Inc.
** See COPYING for distribution information.
*/

#ifndef x_http_clientauthfwd_H
#define x_http_clientauthfwd_H

#include <x/ptrfwd.H>
#include <x/namespace.h>

namespace LIBCXX_NAMESPACE {

	namespace http {
#if 0
	};
};
#endif

class clientauthObj;

//! Collection of authorizations used by an HTTP request.

typedef ref<clientauthObj> clientauth;

#if 0
{
	{
#endif
	}
}

#endif
