/*
** Copyright 2012-2019 Double Precision, Inc.
** See COPYING for distribution information.
*/

#ifndef x_http_clientauthcachefwd_H
#define x_http_clientauthcachefwd_H

#include <x/ptrfwd.H>
#include <x/namespace.h>

namespace LIBCXX_NAMESPACE {

	namespace http {
#if 0
	};
};
#endif

class clientauthcacheObj;

//! Collection of cached authorizations

typedef ref<clientauthcacheObj> clientauthcache;

#if 0
{
	{
#endif
	}
}

#endif
