/*
** Copyright 2012-2020 Double Precision, Inc.
** See COPYING for distribution information.
*/

#ifndef DOXYGEN

namespace LIBCXX_NAMESPACE {
	namespace http {

#if 0
	}
}
#endif

LIBCXX_TEMPLATE_DECL template useragentObj::response
useragentObj::request_with_headers(const fd *,
				   requestimpl &,
				   const std::pair<LIBCXX_TEMPLATE_ITER,
						   LIBCXX_TEMPLATE_ITER> &)
;

LIBCXX_TEMPLATE_DECL template
class useragentObj::request_with_body<LIBCXX_TEMPLATE_ITER>;

#if 0
{
	{
#endif
	}
}
#endif

