/*
** Copyright 2012 Double Precision, Inc.
** See COPYING for distribution information.
*/ 
#ifndef x_yaml_newmappingnodefwd_H
#define x_yaml_newmappingnodefwd_H

#include <x/namespace.h>
#include <x/yaml/newnodefwd.H>
#include <x/ptrfwd.H>

namespace LIBCXX_NAMESPACE {

	namespace yaml {
#if 0
	}
}
#endif

template<typename container_type=std::list<std::pair<const_newnode,
						     const_newnode> > >
struct newmapping;

template<typename container_type, typename functor_type>
class newmappingnodeObj;

#if 0
{
	{
#endif
	}
}

#endif
