/*
** Copyright 2012 Double Precision, Inc.
** See COPYING for distribution information.
*/ 
#ifndef x_yaml_newsequencenodefwd_H
#define x_yaml_newsequencenodefwd_H

#include <x/namespace.h>
#include <x/yaml/newnodefwd.H>
#include <x/ptrfwd.H>

namespace LIBCXX_NAMESPACE {

	namespace yaml {
#if 0
	}
}
#endif

template<typename container_type=std::list<const_newnode> > struct newsequence;

template<typename container_type, typename functor_type>
class newsequencenodeObj;

#if 0
{
	{
#endif
	}
}

#endif
