/*
** Copyright 2012 Double Precision, Inc.
** See COPYING for distribution information.
*/

#ifndef x_docnode_H
#define x_docnode_H

#include <x/namespace.h>
#include <x/yaml/docnodefwd.H>
#include <x/yaml/docnodeobj.H>
#include <x/ref.H>
#include <x/ptr.H>

namespace LIBCXX_NAMESPACE {

	namespace yaml {
#if 0
	}
}
#endif

//! Base class for a node in a YAML document

//! Refer to this class \c yaml::docnode::base

class docnodeBase : public ptrrefBase {
};

#if 0
{
	{
#endif
	}
}
#endif
