/*
** Copyright 2012-2020 Double Precision, Inc.
** See COPYING for distribution information.
*/ 
#ifndef x_yaml_newmappingnodefwd_H
#define x_yaml_newmappingnodefwd_H

#include <x/namespace.h>
#include <x/yaml/newnodefwd.H>
#include <x/ptrfwd.H>

namespace LIBCXX_NAMESPACE::yaml {
#if 0
}
#endif

class newmapping;

template<typename functor_type> class newmappingnodeObj;

#if 0
{
#endif
}

#endif
