/*
** Copyright 2020 Double Precision, Inc.
** See COPYING for distribution information.
*/

LIBCXX_TEMPLATE_DECL
template void docObj::createnodeObj::text<int16_t>(int16_t);
LIBCXX_TEMPLATE_DECL
template void docObj::createnodeObj::text<uint16_t>(uint16_t);
LIBCXX_TEMPLATE_DECL
template void docObj::createnodeObj::text<int32_t>(int32_t);
LIBCXX_TEMPLATE_DECL
template void docObj::createnodeObj::text<uint32_t>(uint32_t);
LIBCXX_TEMPLATE_DECL
template void docObj::createnodeObj::text<int64_t>(int64_t);
LIBCXX_TEMPLATE_DECL
template void docObj::createnodeObj::text<uint64_t>(uint64_t);
