/*
** Copyright 2013 Double Precision, Inc.
** See COPYING for distribution information.
*/

#ifndef x_xml_newdtdobj_H
#define x_xml_newdtdobj_H

#include <x/xml/dtdobj.H>

namespace LIBCXX_NAMESPACE {

	namespace xml {
#if 0
	};
};
#endif

//! A modifiable external or an internal document type.

class newdtdObj : virtual public dtdObj {

public:
	//! Constructor
	newdtdObj();

	//! Destructor
	~newdtdObj() noexcept;
};

#if 0
{
	{
#endif
	}
}
#endif
