/*
** Copyright 2017-2019 Double Precision, Inc.
** See COPYING for distribution information.
*/
#ifndef x_callback_container_fwd_H
#define x_callback_container_fwd_H

#include <x/namespace.h>

namespace LIBCXX_NAMESPACE {
#if 0
};
#endif

template<typename signature, typename container_type>
class callback_container_implBase;

template<typename signature, typename container_type>
class callback_containerObj;

template<typename signature, typename container_t>
class callback_map_or_multimap_impl;

template<typename signature, typename type>
class callback_multimap_impl;

template<typename signature, typename type>
class callback_map_impl;

template<typename signature>
class callback_list_impl;

#if 0
{
#endif
}

#endif
