/*
** Copyright 2020 Double Precision, Inc.
** See COPYING for distribution information.
*/

#ifndef x_refptr_traitsfwd_H
#define x_refptr_traitsfwd_H

#include <x/namespace.h>
#include <x/ptrfwd.H>
#include <type_traits>
#include <utility>

namespace LIBCXX_NAMESPACE {

#if 0
};
#endif

template<typename objClass, typename baseClass,
	 typename type_t> class std_refptr_traits;
#if 0
{
#endif
}
#endif
