/*
** Copyright 2012-2019 Double Precision, Inc.
** See COPYING for distribution information.
*/

#ifndef x_timertaskentryfwd_H
#define x_timertaskentryfwd_H

#include <x/ref.H>
#include <x/ptr.H>

namespace LIBCXX_NAMESPACE {
#if 0
};
#endif

class timertaskentryObj;

//! An internal timer task entry object

//! \internal
typedef ref<timertaskentryObj> timertaskentry;

//! An internal timer task entry object

//! \internal
typedef ptr<timertaskentryObj> timertaskentryptr;

#if 0
{
#endif
}
#endif
