/*
** Copyright 2012 Double Precision, Inc.
** See COPYING for distribution information.
*/ 
#ifndef x_mime_tokens_H
#define x_mime_tokens_H

#include <x/namespace.h>

namespace LIBCXX_NAMESPACE {

	namespace mime {
#if 0
	}
}
#endif

//! EOF token
static const int eof= -1;

//! Start of newline sequence
static const int newline_start=0x0100;

//! End of newline sequence
static const int newline_end=0x0101;

//! Start of message body
static const int body_start=0x0102;

#if 0
{
	{
#endif
	}
}
#endif
